print(" I will now count my chickens:")
print("Hens", 25 + 30 /6)
print("Roosters", 100-25*3%4)
print("Now i will count the eggs:")
print("is it true that 3+2<5 -7?")
print(3+2<5-7)
print("what is 3+2?", 3+2)
print("what is 5-7?", 5-7)
print("oh, that's why it's false")
print("how about some more.")
print("is it greater?", 5>-2)
